myportfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path("", views.index, name="index"),
    path("send", views.send, name="send"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("message", views.message, name="message"),
    path("admin_login", views.admin_login, name="admin_login"),
    path("log_out", views.log_out, name="log_out"),
]

portfolio/models.py
from django.db import models
from datetime import datetime
# Create your models here.


class Message(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    project = models.CharField(max_length=1000)
    message = models.CharField(max_length=100000)
    date = models.DateTimeField(default=datetime.now, blank=True)
    def __str__(self):
        return self.firstname
    

portfolio/forms.py
from django import forms
from .models import *


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields ="__all__"

portfolio/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.html import strip_tags
from .models import *
from .forms import *

# Create your views here.
def index(request):
    messages_count = Message.objects.all().count()
    context = {
        'messages_count':messages_count
        }
    return render(request, 'portfolio/index.html', context)

# ******************* SEND VIEW *****************************
def send(request):
    if request.method =='POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Message successfully sent")
            return redirect(request.META.get("HTTP_REFERER"))

        else:
            for field, error in form.errors.items():
                error = strip_tags(error)
                messages.error(request,f"{field}: {error}")
                return redirect(request.META.get("HTTP_REFERER"))



# ******************* ADMIN PAGE VIEW *****************************
@login_required(login_url="portfolio:admin_login")   
def dashboard(request):
    return render(request, 'dashboard/home.html')


# ******************* ADMIN MESSAGE *****************************
@login_required(login_url="portfolio:admin_login")   
def message(request):
    messages_count = Message.objects.all().count()
    messages = Message.objects.all().order_by("-id")
    context = {
        'messages': messages,
        'messages_count':messages_count
    }
    return render(request, 'dashboard/message.html', context)

# ******************* ADMIN LOGIN *****************************
def admin_login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None and user.is_staff and user.is_superuser:
            login(request, user)
            return redirect('portfolio:dashboard')

        else:
            messages.error(request, "Invalid Credential")
            return redirect("portfolio:admin_login")

    return render(request, 'dashboard/login.html')

# ******************* ADMIN LOGOUT  VIEW *****************************
def log_out(request):
    logout(request)
    messages.success(request, "You have successfully logged out")
    return redirect("portfolio:admin_login")

templates/dashboard/home.html
{% extends 'home/base.html'%}
{% block title %}DASHBOARD{% endblock %}
{% block content%}
{% include 'home/card.html'%}



<!--Graphs-->

<div class="container">
    <div class="row my-5">
        <div class="col-md-6">
            <div class="bg-white">
                <canvas id="myChart1" width="400" height="300"></canvas>
                <script>
                    var ctx = document.getElementById('myChart1').getContext('2d');
                    var myChart1 = new Chart(ctx, {
                        type: 'pie',
                        data: {
                            labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
                            datasets: [{
                                label: 'Reviews',
                                data: [12, 19, 3, 5, 2, 3],
                                backgroundColor: [
                                    'rgba(255, 99, 132, 1)',
                                    'rgba(54, 162, 235, 1)',
                                    'rgba(255, 206, 86, 1)',
                                    'rgba(75, 192, 192, 1)',
                                    'rgba(153, 102, 255, 1)',
                                    'rgba(255, 159, 64, 1)'
                                ],
                                borderColor: [
                                    'rgba(255, 99, 132, 1)',
                                    'rgba(54, 162, 235, 1)',
                                    'rgba(255, 206, 86, 1)',
                                    'rgba(75, 192, 192, 1)',
                                    'rgba(153, 102, 255, 1)',
                                    'rgba(255, 159, 64, 1)'
                                ],
                                borderWidth: 1
                            }]
                        },
                        options: {
                            scales: {
                                yAxes: [{
                                    ticks: {
                                        beginAtZero: true
                                    }
                                }]
                            }
                        }
                    });
                </script>
            </div>
        </div>
        <div class="col-md-6">
            <div class="bg-white">
                <canvas id="myChart" width="400" height="300"></canvas>
                <script>
                    var ctx = document.getElementById('myChart').getContext('2d');
                    var myChart = new Chart(ctx, {
                        type: 'bar',
                        data: {
                            labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
                            datasets: [{
                                label: 'Reviews',
                                data: [12, 19, 3, 5, 2, 3],
                                backgroundColor: [
                                    'rgba(255, 99, 132, 1)',
                                    'rgba(54, 162, 235, 1)',
                                    'rgba(255, 206, 86, 1)',
                                    'rgba(75, 192, 192, 1)',
                                    'rgba(153, 102, 255, 1)',
                                    'rgba(255, 159, 64, 1)'
                                ],
                                borderColor: [
                                    'rgba(255, 99, 132, 1)',
                                    'rgba(54, 162, 235, 1)',
                                    'rgba(255, 206, 86, 1)',
                                    'rgba(75, 192, 192, 1)',
                                    'rgba(153, 102, 255, 1)',
                                    'rgba(255, 159, 64, 1)'
                                ],
                                borderWidth: 1
                            }]
                        },
                        options: {
                            scales: {
                                yAxes: [{
                                    ticks: {
                                        beginAtZero: true
                                    }
                                }]
                            }
                        }
                    });
                </script>
            </div>
        </div>
    </div>
</div>
<!--End Graphs-->

{% endblock%}

templates/dashboard/login.html
<head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <link rel="icon" type="image/x-icon" href="{% static 'img/logo.png'%}">

    <link rel="stylesheet" href="{% static 'css/reset.css'%}" />
</head>

<body style="background-color: #301e4e;">
    <main style="background-color: #301e4e;">
        <section class="login-container">
            <div class="login">
                <h1>Admin login</h1>
                {% for message in messages %}
                <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                    {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}

                <form action="" method="post">
                    {% csrf_token %}

                    <div class="form-control">
                        <label for="email">Username</label>
                        <input type="text" name="username" placeholder="Enter your Username" required />
                    </div>
                    <div class="form-control">
                        <label for="password">Password</label>
                        <input type="password" name="password" id="password" placeholder="Enter your password"
                            required />
                    </div>
                    <div class="form-action">
                        <button style="cursor: pointer;">Login</button>
                    </div>
                </form>
            </div>
        </section>
    </main>
    <footer></footer>

    <script src="{% static 'js/login.js'%}"></script>
</body>

</html>

templates/dashboard/message.html
{% extends 'home/base.html'%}
{% block title %}MESSAGES{% endblock %}
{% block content%}
{% include 'home/card.html'%}



<!--Graphs-->

<div class="container">
    <div class="row my-4">
        <div class="col-md-12">
            <table class="table bg-white">
                <thead class="" style="background:  #301e4e;">
                    <tr class="text-white">
                        <th scope="col">Firstname</th>
                        <th scope="col">Lastname</th>
                        <th scope="col">Email</th>
                        <th scope="col">Message</th>
                    </tr>
                </thead>
                <tbody>
                    {% for message in messages %}
                    <tr>
                        <td>{{message.firstname}}</td>
                        <td>{{message.lastname}}</td>
                        <td>{{message.email}}</td>
                        <td> <textarea name="" id="" cols="30" rows="4"
                                style="outline: none; border: none; resize: none;">{{message.message}}</textarea></td>

                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>

</div>
<!--End Table-->
{% endblock%}

templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <meta charset="utf-8" />
    <meta name="referrer" content="no-referrer-when-downgrade">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" />
    <!-- Bootstrap CSS -->
    <link rel="icon" type="image/x-icon" href="{% static 'img/logo.png'%}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous" />

    <!--FontAwesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"
        integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous" />
    <script src="https://kit.fontawesome.com/95a0b08006.js" crossorigin="anonymous"></script>

    <!--Chartjs CDN-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"></script>
    <!-- CSS -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <!-- Bootstrap theme -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/bootstrap.min.css" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <!----css3---->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
    <!-- SLIDER REVOLUTION 4.x CSS SETTINGS -->

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
        rel="stylesheet" />

    <!--google material icon-->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet" />
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <div class="wrapper">
        <div class="body-overlay"></div>

        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <li>
                    <a href=""><img src="" class="img-fluid" /></a><span class="title"
                        style="font-size:1.5rem ;">CODEX</span>
                </li>
            </div>
            <ul class="list-unstyled components">
                <li class="active">
                    <a href="{% url 'portfolio:dashboard' %}" class="dashboard"><i
                            class="material-icons">dashboard</i><span>Dashboard</span></a>
                </li>

                <div class="small-screen navbar-display">



                    <li class="d-lg-none d-md-block d-xl-none d-sm-block">
                        <a href="{% url 'portfolio:log_out' %}"><i class="fas fa-sign-out"></i><span>Logout</span></a>
                    </li>
                </div>


                <li class="item">
                    <a href="{% url 'portfolio:message' %}"><i class="fas fa-envelope"></i><span>message</span></a>
                </li>
                </li>





        </nav>

        <!-- Page Content  -->
        <div id="content">
            <div class="top-navbar">
                <nav class="navbar navbar-expand-lg">
                    <div class="container-fluid">
                        <button type="button" id="sidebarCollapse" class="d-xl-block d-lg-block d-md-mone d-none">
                            <span class="material-icons">arrow_back_ios</span>
                        </button>

                        <a class="navbar-brand" href="{% url 'portfolio:dashboard' %}"> Dashboard </a>

                        <button class="d-inline-block d-lg-none ml-auto more-button" type="button"
                            data-toggle="collapse" data-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="material-icons">more_vert</span>
                        </button>

                        <div class="collapse navbar-collapse d-lg-block d-xl-block d-sm-none d-md-none d-none"
                            id="navbarSupportedContent">
                            <ul class="nav navbar-nav ml-auto">



                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'portfolio:log_out' %}" style="color: inherit;">
                                        <i class="fas fa-sign-out"></i><span></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </div>

            <div class="main-content">
                <!--End Topside-->

                {% block content%}
                {% endblock%}
            </div>
        </div>
    </div>

    <!--Start of Tawk.to Script-->
    <!--Start of Tawk.to Script-->
    <!--End of Tawk.to Script-->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
    <script> alertify.set('notifier', 'position', 'top-right');
        {% for msg in messages %}
        alertify.success('{{msg}}');
        {% endfor %}
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebarCollapse").on("click", function () {
                $("#sidebar").toggleClass("active");
                $("#content").toggleClass("active");
            });

            $(".more-button,.body-overlay").on("click", function () {
                $("#sidebar,.body-overlay").toggleClass("show-nav");
            });
        });
    </script>
</body>

</html>

templates/home/card.html
<!--Topside-->
<div class="container">
    <div class="row mt-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header text-white" style="background-color: #301e4e;">
                    Statistics
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6 mb-4">
                            <a class="text-decoration-none text-dark" href="">
                                <div class="card my-card shadow text-center p-3 text-white "
                                    style="background-color: #301e4e;">
                                    <h4>Reviews</h4>
                                    <h3>{{reviews_count}}</h3>
                                </div>
                            </a>
                        </div>

                        <div class="col-md-6">
                            <a class="text-decoration-none text-dark" href="">
                                <div class="card my-card shadow text-center p-3 text-white"
                                    style="background-color: #301e4e;">
                                    <h4>Messages
                                    </h4>
                                    <h3>{{messages_count}}</h3>
                                </div>
                            </a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>